// products.filter(p=>p.tags.include('new'))
/**
 * for high rated shits
 * products.filter(p=>{
 *   const avg = p.ratings.reduce((a,b)=>a+b,0);
 *   if(avg>=4.5)
 *      p.highrated=true;/return that shit?
 * })
 */

/**
 * FLow of buy
 * changes anytime =>cart,quantity,price,tags
 * things will happen on every purchase
 * user -> carts theke remove(quantity wise)->history add -> ratings dibe
 * payProcess=> product available,payment method validation,
 * products-> stock update->saleHistory update->ratings update
 */

//total 48 entries on db now

export const categories = [
  {
    name: "electronics",
    quantity: 10,
  },
  {
    name: "fashion",
    quantity: 8,
  },
  {
    name: "home",
    quantity: 9,
  },
  {
    name: "beauty",
    quantity: 7,
  },
  {
    name: "sports",
    quantity: 8,
  },
  {
    name: "books",
    quantity: 6,
  },
];

export const products = [
  // Electronics (10 products)
  {
    id: "p1",
    name: "Wireless Headphones",
    description: "Noise-canceling over-ear headphones",
    price: 129.99,
    originalPrice: 179.99,
    category: "electronics",
    image: "/images/products/headphones.jpg",
    tags: ["new", "trending"],
    saleHistory: [
      { userId: "u1", date: "2024-01-15", quantity: 2 },
      { userId: "u3", date: "2024-01-20", quantity: 1 },
      { userId: "u6", date: "2024-02-01", quantity: 3 },
    ],
    isDealOfDay: true,
    isBestSeller: true,
    ratings: [5, 4, 5, 3],
    stock: 30,
  },
  {
    id: "p2",
    name: "Smartphone",
    description: "Latest Android smartphone with 128GB storage",
    price: 299.99,
    originalPrice: 399.99,
    category: "electronics",
    image: "/images/products/smartphone.jpg",
    tags: ["trending", "topRated"],
    saleHistory: [
      { userId: "u2", date: "2024-01-10", quantity: 1 },
      { userId: "u4", date: "2024-01-25", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [5, 5, 4, 5],
    stock: 25,
  },
  {
    id: "p3",
    name: "Laptop",
    description: "14-inch ultrabook with SSD",
    price: 599.99,
    originalPrice: 799.99,
    category: "electronics",
    image: "/images/products/laptop.jpg",
    tags: ["new"],
    saleHistory: [{ userId: "u1", date: "2024-02-05", quantity: 1 }],
    isDealOfDay: true,
    isBestSeller: false,
    ratings: [4, 5, 5],
    stock: 12,
  },
  {
    id: "p4",
    name: "Smart Watch",
    description: "Fitness tracking smartwatch",
    price: 199.99,
    originalPrice: 249.99,
    category: "electronics",
    image: "/images/products/smartwatch.jpg",
    tags: ["trending"],
    saleHistory: [
      { userId: "u5", date: "2024-01-30", quantity: 2 },
      { userId: "u7", date: "2024-02-10", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [4, 4, 5, 3, 4],
    stock: 40,
  },
  {
    id: "p5",
    name: "Bluetooth Speaker",
    description: "Portable wireless speaker",
    price: 39.99,
    originalPrice: 59.99,
    category: "electronics",
    image: "/images/products/speaker.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u3", date: "2024-01-18", quantity: 3 },
      { userId: "u8", date: "2024-02-02", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [5, 4, 5, 5],
    stock: 60,
  },
  {
    id: "p6",
    name: "Gaming Mouse",
    description: "RGB gaming mouse with programmable buttons",
    price: 49.99,
    originalPrice: 69.99,
    category: "electronics",
    image: "/images/products/mouse.jpg",
    tags: ["new", "trending"],
    saleHistory: [{ userId: "u2", date: "2024-02-08", quantity: 1 }],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 5, 4],
    stock: 35,
  },
  {
    id: "p7",
    name: "Tablet",
    description: "10-inch Android tablet",
    price: 199.99,
    originalPrice: 249.99,
    category: "electronics",
    image: "/images/products/tablet.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u6", date: "2024-01-22", quantity: 1 },
      { userId: "u9", date: "2024-02-12", quantity: 2 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [5, 4, 4, 5, 3],
    stock: 20,
  },
  {
    id: "p8",
    name: "Webcam",
    description: "HD webcam for video calls",
    price: 79.99,
    originalPrice: 99.99,
    category: "electronics",
    image: "/images/products/webcam.jpg",
    tags: ["new"],
    saleHistory: [{ userId: "u4", date: "2024-02-06", quantity: 1 }],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 4, 5],
    stock: 45,
  },
  {
    id: "p9",
    name: "Power Bank",
    description: "20000mAh portable charger",
    price: 29.99,
    originalPrice: 39.99,
    category: "electronics",
    image: "/images/products/powerbank.jpg",
    tags: ["trending", "topRated"],
    saleHistory: [
      { userId: "u7", date: "2024-01-28", quantity: 2 },
      { userId: "u10", date: "2024-02-14", quantity: 1 },
    ],
    isDealOfDay: true,
    isBestSeller: true,
    ratings: [5, 5, 4, 5],
    stock: 80,
  },
  {
    id: "p10",
    name: "USB-C Hub",
    description: "7-in-1 USB-C hub with HDMI",
    price: 34.99,
    originalPrice: 49.99,
    category: "electronics",
    image: "/images/products/usbhub.jpg",
    tags: ["new"],
    saleHistory: [{ userId: "u1", date: "2024-02-03", quantity: 1 }],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 5, 4, 4],
    stock: 55,
  },

  // Fashion (8 products)
  {
    id: "p11",
    name: "Men T-Shirt",
    description: "100% Cotton stylish tee",
    price: 19.99,
    originalPrice: 25.0,
    category: "fashion",
    image: "/images/products/tshirt.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u1", date: "2024-01-12", quantity: 2 },
      { userId: "u3", date: "2024-01-24", quantity: 1 },
      { userId: "u6", date: "2024-02-07", quantity: 3 },
    ],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 5],
    stock: 50,
  },
  {
    id: "p12",
    name: "Women's Dress",
    description: "Elegant summer dress",
    price: 79.99,
    originalPrice: 99.99,
    category: "fashion",
    image: "/images/products/dress.jpg",
    tags: ["trending", "new"],
    saleHistory: [
      { userId: "u2", date: "2024-01-16", quantity: 1 },
      { userId: "u8", date: "2024-02-01", quantity: 2 },
    ],
    isDealOfDay: true,
    isBestSeller: true,
    ratings: [5, 4, 5, 5],
    stock: 25,
  },
  {
    id: "p13",
    name: "Jeans",
    description: "Classic blue denim jeans",
    price: 59.99,
    originalPrice: 79.99,
    category: "fashion",
    image: "/images/products/jeans.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u5", date: "2024-01-19", quantity: 1 },
      { userId: "u9", date: "2024-02-11", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [4, 4, 5, 4],
    stock: 40,
  },
  {
    id: "p14",
    name: "Sneakers",
    description: "Comfortable running sneakers",
    price: 89.99,
    originalPrice: 119.99,
    category: "fashion",
    image: "/images/products/sneakers.jpg",
    tags: ["trending"],
    saleHistory: [
      { userId: "u4", date: "2024-02-04", quantity: 1 },
      { userId: "u7", date: "2024-02-13", quantity: 2 },
    ],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [5, 4, 4, 5, 3],
    stock: 30,
  },
  {
    id: "p15",
    name: "Leather Jacket",
    description: "Genuine leather biker jacket",
    price: 199.99,
    originalPrice: 279.99,
    category: "fashion",
    image: "/images/products/jacket.jpg",
    tags: ["new"],
    saleHistory: [{ userId: "u6", date: "2024-01-31", quantity: 1 }],
    isDealOfDay: true,
    isBestSeller: false,
    ratings: [5, 5, 4],
    stock: 15,
  },
  {
    id: "p16",
    name: "Handbag",
    description: "Designer leather handbag",
    price: 149.99,
    originalPrice: 199.99,
    category: "fashion",
    image: "/images/products/handbag.jpg",
    tags: ["topRated", "trending"],
    saleHistory: [
      { userId: "u10", date: "2024-02-09", quantity: 1 },
      { userId: "u3", date: "2024-02-15", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [5, 5, 4, 5],
    stock: 22,
  },
  {
    id: "p17",
    name: "Sunglasses",
    description: "UV protection sunglasses",
    price: 39.99,
    originalPrice: 59.99,
    category: "fashion",
    image: "/images/products/sunglasses.jpg",
    tags: ["new"],
    saleHistory: [{ userId: "u2", date: "2024-02-12", quantity: 2 }],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 4, 5, 3],
    stock: 65,
  },
  {
    id: "p18",
    name: "Watch",
    description: "Classic analog wristwatch",
    price: 129.99,
    originalPrice: 169.99,
    category: "fashion",
    image: "/images/products/watch.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u8", date: "2024-01-26", quantity: 1 },
      { userId: "u1", date: "2024-02-08", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [5, 4, 5, 5, 4],
    stock: 18,
  },

  // Home (9 products)
  {
    id: "p19",
    name: "Blender",
    description: "Multi-speed kitchen blender",
    price: 49.99,
    originalPrice: 59.99,
    category: "home",
    image: "/images/products/blender.jpg",
    tags: ["new"],
    saleHistory: [
      { userId: "u1", date: "2024-01-14", quantity: 1 },
      { userId: "u3", date: "2024-01-29", quantity: 1 },
      { userId: "u6", date: "2024-02-06", quantity: 2 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [5, 5, 4, 5, 4],
    stock: 15,
  },
  {
    id: "p20",
    name: "Coffee Maker",
    description: "Automatic drip coffee maker",
    price: 79.99,
    originalPrice: 99.99,
    category: "home",
    image: "/images/products/coffeemaker.jpg",
    tags: ["trending", "topRated"],
    saleHistory: [
      { userId: "u5", date: "2024-01-21", quantity: 1 },
      { userId: "u9", date: "2024-02-10", quantity: 1 },
    ],
    isDealOfDay: true,
    isBestSeller: true,
    ratings: [5, 4, 5, 4, 5],
    stock: 28,
  },
  {
    id: "p21",
    name: "Vacuum Cleaner",
    description: "Cordless stick vacuum",
    price: 199.99,
    originalPrice: 249.99,
    category: "home",
    image: "/images/products/vacuum.jpg",
    tags: ["new"],
    saleHistory: [{ userId: "u2", date: "2024-02-02", quantity: 1 }],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 5, 4, 4],
    stock: 20,
  },
  {
    id: "p22",
    name: "Toaster",
    description: "2-slice stainless steel toaster",
    price: 39.99,
    originalPrice: 49.99,
    category: "home",
    image: "/images/products/toaster.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u7", date: "2024-01-17", quantity: 1 },
      { userId: "u4", date: "2024-02-14", quantity: 2 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [4, 4, 5, 4],
    stock: 45,
  },
  {
    id: "p23",
    name: "Bed Sheets",
    description: "Egyptian cotton bed sheet set",
    price: 69.99,
    originalPrice: 89.99,
    category: "home",
    image: "/images/products/bedsheets.jpg",
    tags: ["trending"],
    saleHistory: [
      { userId: "u10", date: "2024-01-23", quantity: 1 },
      { userId: "u8", date: "2024-02-05", quantity: 2 },
    ],
    isDealOfDay: true,
    isBestSeller: false,
    ratings: [5, 5, 4, 5],
    stock: 35,
  },
  {
    id: "p24",
    name: "Lamp",
    description: "Modern table lamp with LED",
    price: 89.99,
    originalPrice: 119.99,
    category: "home",
    image: "/images/products/lamp.jpg",
    tags: ["new"],
    saleHistory: [{ userId: "u6", date: "2024-02-01", quantity: 1 }],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 5, 4],
    stock: 25,
  },
  {
    id: "p25",
    name: "Curtains",
    description: "Blackout window curtains",
    price: 29.99,
    originalPrice: 39.99,
    category: "home",
    image: "/images/products/curtains.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u3", date: "2024-01-27", quantity: 3 },
      { userId: "u1", date: "2024-02-11", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [4, 4, 5, 4, 3],
    stock: 50,
  },
  {
    id: "p26",
    name: "Kitchen Scale",
    description: "Digital kitchen scale",
    price: 24.99,
    originalPrice: 34.99,
    category: "home",
    image: "/images/products/scale.jpg",
    tags: ["new", "trending"],
    saleHistory: [{ userId: "u9", date: "2024-02-07", quantity: 1 }],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [5, 4, 4, 5],
    stock: 40,
  },
  {
    id: "p27",
    name: "Storage Boxes",
    description: "Set of 3 storage organizer boxes",
    price: 34.99,
    originalPrice: 44.99,
    category: "home",
    image: "/images/products/storage.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u5", date: "2024-01-25", quantity: 2 },
      { userId: "u2", date: "2024-02-13", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [4, 5, 4, 4, 5],
    stock: 60,
  },

  // Beauty (7 products)
  {
    id: "p28",
    name: "Face Cream",
    description: "Anti-aging moisturizing cream",
    price: 49.99,
    originalPrice: 69.99,
    category: "beauty",
    image: "/images/products/facecream.jpg",
    tags: ["trending", "topRated"],
    saleHistory: [
      { userId: "u8", date: "2024-01-18", quantity: 2 },
      { userId: "u10", date: "2024-02-04", quantity: 1 },
    ],
    isDealOfDay: true,
    isBestSeller: true,
    ratings: [5, 5, 4, 5, 4],
    stock: 30,
  },
  {
    id: "p29",
    name: "Lipstick",
    description: "Long-lasting matte lipstick",
    price: 19.99,
    originalPrice: 24.99,
    category: "beauty",
    image: "/images/products/lipstick.jpg",
    tags: ["new"],
    saleHistory: [
      { userId: "u3", date: "2024-01-20", quantity: 3 },
      { userId: "u7", date: "2024-02-09", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 5, 4, 4],
    stock: 75,
  },
  {
    id: "p30",
    name: "Shampoo",
    description: "Organic sulfate-free shampoo",
    price: 16.99,
    originalPrice: 21.99,
    category: "beauty",
    image: "/images/products/shampoo.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u4", date: "2024-01-15", quantity: 2 },
      { userId: "u6", date: "2024-02-12", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [5, 4, 5, 5],
    stock: 55,
  },
  {
    id: "p31",
    name: "Foundation",
    description: "Full coverage liquid foundation",
    price: 39.99,
    originalPrice: 49.99,
    category: "beauty",
    image: "/images/products/foundation.jpg",
    tags: ["trending"],
    saleHistory: [
      { userId: "u1", date: "2024-02-01", quantity: 1 },
      { userId: "u9", date: "2024-02-15", quantity: 2 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [4, 4, 5, 4, 3],
    stock: 42,
  },
  {
    id: "p32",
    name: "Eye Shadow Palette",
    description: "12-color eyeshadow palette",
    price: 29.99,
    originalPrice: 39.99,
    category: "beauty",
    image: "/images/products/eyeshadow.jpg",
    tags: ["new", "trending"],
    saleHistory: [{ userId: "u2", date: "2024-01-28", quantity: 1 }],
    isDealOfDay: true,
    isBestSeller: false,
    ratings: [5, 4, 5, 4],
    stock: 38,
  },
  {
    id: "p33",
    name: "Perfume",
    description: "Floral fragrance perfume 50ml",
    price: 79.99,
    originalPrice: 99.99,
    category: "beauty",
    image: "/images/products/perfume.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u5", date: "2024-02-03", quantity: 1 },
      { userId: "u8", date: "2024-02-14", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [5, 5, 4, 5, 5],
    stock: 25,
  },
  {
    id: "p34",
    name: "Face Mask",
    description: "Hydrating sheet face mask pack",
    price: 12.99,
    originalPrice: 16.99,
    category: "beauty",
    image: "/images/products/facemask.jpg",
    tags: ["new"],
    saleHistory: [
      { userId: "u10", date: "2024-01-30", quantity: 4 },
      { userId: "u7", date: "2024-02-08", quantity: 2 },
    ],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 4, 5, 4, 4],
    stock: 80,
  },

  // Sports (8 products)
  {
    id: "p35",
    name: "Yoga Mat",
    description: "Non-slip exercise yoga mat",
    price: 24.99,
    originalPrice: 34.99,
    category: "sports",
    image: "/images/products/yogamat.jpg",
    tags: ["trending", "topRated"],
    saleHistory: [
      { userId: "u6", date: "2024-01-22", quantity: 1 },
      { userId: "u4", date: "2024-02-05", quantity: 2 },
    ],
    isDealOfDay: true,
    isBestSeller: true,
    ratings: [5, 4, 5, 4, 5],
    stock: 45,
  },
  {
    id: "p36",
    name: "Dumbbells",
    description: "Adjustable weight dumbbells set",
    price: 89.99,
    originalPrice: 119.99,
    category: "sports",
    image: "/images/products/dumbbells.jpg",
    tags: ["new"],
    saleHistory: [
      { userId: "u1", date: "2024-01-16", quantity: 1 },
      { userId: "u9", date: "2024-02-10", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 5, 4, 4],
    stock: 20,
  },
  {
    id: "p37",
    name: "Basketball",
    description: "Official size basketball",
    price: 29.99,
    originalPrice: 39.99,
    category: "sports",
    image: "/images/products/basketball.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u3", date: "2024-01-19", quantity: 1 },
      { userId: "u8", date: "2024-02-13", quantity: 2 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [5, 4, 5, 5],
    stock: 35,
  },
  {
    id: "p38",
    name: "Water Bottle",
    description: "Stainless steel water bottle 750ml",
    price: 19.99,
    originalPrice: 24.99,
    category: "sports",
    image: "/images/products/waterbottle.jpg",
    tags: ["trending"],
    saleHistory: [
      { userId: "u2", date: "2024-02-02", quantity: 3 },
      { userId: "u7", date: "2024-02-11", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [4, 4, 5, 4, 4],
    stock: 70,
  },
  {
    id: "p39",
    name: "Running Shoes",
    description: "Lightweight running shoes",
    price: 119.99,
    originalPrice: 159.99,
    category: "sports",
    image: "/images/products/runningshoes.jpg",
    tags: ["new", "trending"],
    saleHistory: [
      { userId: "u5", date: "2024-01-24", quantity: 1 },
      { userId: "u10", date: "2024-02-07", quantity: 1 },
    ],
    isDealOfDay: true,
    isBestSeller: false,
    ratings: [5, 4, 4, 5, 3],
    stock: 28,
  },
  {
    id: "p40",
    name: "Resistance Bands",
    description: "Set of 5 resistance exercise bands",
    price: 16.99,
    originalPrice: 22.99,
    category: "sports",
    image: "/images/products/bands.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u4", date: "2024-01-26", quantity: 2 },
      { userId: "u1", date: "2024-02-14", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [4, 5, 4, 5, 4],
    stock: 55,
  },
  {
    id: "p41",
    name: "Protein Powder",
    description: "Whey protein powder 2lb",
    price: 39.99,
    originalPrice: 49.99,
    category: "sports",
    image: "/images/products/protein.jpg",
    tags: ["new"],
    saleHistory: [
      { userId: "u6", date: "2024-02-04", quantity: 1 },
      { userId: "u9", date: "2024-02-12", quantity: 2 },
    ],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [5, 4, 4, 5],
    stock: 40,
  },
  {
    id: "p42",
    name: "Tennis Racket",
    description: "Professional tennis racket",
    price: 149.99,
    originalPrice: 199.99,
    category: "sports",
    image: "/images/products/racket.jpg",
    tags: ["topRated"],
    saleHistory: [{ userId: "u8", date: "2024-01-21", quantity: 1 }],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [5, 5, 4, 5, 4],
    stock: 15,
  },

  // Books (6 products)
  {
    id: "p43",
    name: "Fiction Novel",
    description: "Bestselling mystery novel",
    price: 14.99,
    originalPrice: 19.99,
    category: "books",
    image: "/images/products/novel.jpg",
    tags: ["trending", "topRated"],
    saleHistory: [
      { userId: "u3", date: "2024-01-17", quantity: 2 },
      { userId: "u7", date: "2024-02-06", quantity: 1 },
    ],
    isDealOfDay: true,
    isBestSeller: true,
    ratings: [5, 4, 5, 5, 4],
    stock: 65,
  },
  {
    id: "p44",
    name: "Cookbook",
    description: "Healthy cooking recipes book",
    price: 24.99,
    originalPrice: 29.99,
    category: "books",
    image: "/images/products/cookbook.jpg",
    tags: ["new"],
    saleHistory: [
      { userId: "u5", date: "2024-01-23", quantity: 1 },
      { userId: "u2", date: "2024-02-09", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 5, 4, 4],
    stock: 35,
  },
  {
    id: "p45",
    name: "Self-Help Book",
    description: "Personal development and motivation",
    price: 16.99,
    originalPrice: 21.99,
    category: "books",
    image: "/images/products/selfhelp.jpg",
    tags: ["topRated"],
    saleHistory: [
      { userId: "u10", date: "2024-01-25", quantity: 1 },
      { userId: "u4", date: "2024-02-11", quantity: 2 },
    ],
    isDealOfDay: false,
    isBestSeller: true,
    ratings: [5, 4, 5, 4, 5],
    stock: 50,
  },
  {
    id: "p46",
    name: "Science Textbook",
    description: "Introduction to Physics textbook",
    price: 89.99,
    originalPrice: 119.99,
    category: "books",
    image: "/images/products/textbook.jpg",
    tags: ["new"],
    saleHistory: [
      { userId: "u1", date: "2024-02-01", quantity: 1 },
      { userId: "u6", date: "2024-02-13", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 4, 5, 3],
    stock: 25,
  },
  {
    id: "p47",
    name: "Children's Book",
    description: "Illustrated adventure story for kids",
    price: 12.99,
    originalPrice: 16.99,
    category: "books",
    image: "/images/products/childrens.jpg",
    tags: ["trending"],
    saleHistory: [
      { userId: "u8", date: "2024-01-20", quantity: 3 },
      { userId: "u9", date: "2024-02-08", quantity: 2 },
    ],
    isDealOfDay: true,
    isBestSeller: true,
    ratings: [5, 5, 4, 5],
    stock: 45,
  },
  {
    id: "p48",
    name: "Biography",
    description: "Inspiring life story of a famous entrepreneur",
    price: 19.99,
    originalPrice: 24.99,
    category: "books",
    image: "/images/products/biography.jpg",
    tags: ["topRated", "new"],
    saleHistory: [
      { userId: "u3", date: "2024-01-28", quantity: 1 },
      { userId: "u7", date: "2024-02-15", quantity: 1 },
    ],
    isDealOfDay: false,
    isBestSeller: false,
    ratings: [4, 5, 4, 4, 5],
    stock: 40,
  },
];
